[ERROR] ME(1850293:281472885866528,MainProcess):2024-11-09-10:45:43.250.914 [mindspore/run_check/_check_version.py:388] CheckFailed: cannot import name 'utils' from partially initialized module 'tbe.common' (most likely due to a circular import) (/home/miniconda3/envs/ms2.2/lib/python3.8/site-packages/tbe/common/__init__.py)
[ERROR] ME(1850293:281472885866528,MainProcess):2024-11-09-10:45:43.251.220 [mindspore/run_check/_check_version.py:389] MindSpore relies on whl packages of "te" and "hccl" in the "latest" folder of the Ascend AI software package (Ascend Data Center Solution). Please check whether they are installed correctly or not, refer to the match info on: https://www.mindspore.cn/install
[WARNING] COMMON(1850293,ffff83604020,python):2024-11-09-10:45:52.097.709 [mindspore/ccsrc/common/duplex_pipe.cc:111] Read] [DuplexPipe] Read was interrupted by system interrupt, retry: 0
[WARNING] COMMON(1850293,ffff83604020,python):2024-11-09-10:45:52.171.513 [mindspore/ccsrc/common/duplex_pipe.cc:111] Read] [DuplexPipe] Read was interrupted by system interrupt, retry: 1
[WARNING] COMMON(1850293,ffff83604020,python):2024-11-09-10:45:52.597.839 [mindspore/ccsrc/common/duplex_pipe.cc:111] Read] [DuplexPipe] Read was interrupted by system interrupt, retry: 2
[ERROR] COMMON(1850293,ffff83604020,python):2024-11-09-10:45:52.597.899 [mindspore/ccsrc/common/duplex_pipe.cc:114] Read] [DuplexPipe] Read from pipe failed, try 3 times, reason = Interrupted system call
Traceback (most recent call last):
  File "../eval.py", line 109, in <module>
    eval_file(_feature_file, _out_file, _model, _enc, _dec)
  File "../eval.py", line 45, in eval_file
    state1 = mnp.zeros((1, 1, model.rnn_units1))
  File "/home/miniconda3/envs/ms2.2/lib/python3.8/site-packages/mindspore/numpy/array_creations.py", line 334, in zeros
    output = F.fill(dtype, shape, 0)
  File "/home/miniconda3/envs/ms2.2/lib/python3.8/site-packages/mindspore/ops/function/array_func.py", line 746, in fill
    return _get_cache_prim(P.FillV2)()(shape, value)
  File "/home/miniconda3/envs/ms2.2/lib/python3.8/site-packages/mindspore/ops/primitive.py", line 314, in __call__
    return _run_op(self, self.name, args)
  File "/home/miniconda3/envs/ms2.2/lib/python3.8/site-packages/mindspore/ops/primitive.py", line 913, in _run_op
    stub = _pynative_executor.run_op_async(obj, op_name, args)
  File "/home/miniconda3/envs/ms2.2/lib/python3.8/site-packages/mindspore/common/api.py", line 1186, in run_op_async
    return self._executor.run_op_async(*args)
RuntimeError: Response is empty. For more details, please refer to this FAQ: https://www.mindspore.cn/tutorials/zh-CN/master/advanced/error_analysis/mindrt_debug.html

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/ascend/kernel/tbe/tbe_kernel_compile.cc:400 DispatchCompileTask
mindspore/ccsrc/backend/common/session/kernel_build_client.h:103 Response

