[WARNING] ME(335241:281473363402784,MainProcess):2024-10-27-08:08:33.550.029 [mindspore/run_check/_check_version.py:280] Using custom Ascend AI software package (Ascend Data Center Solution) path, package version checking is skipped, please make sure Ascend AI software package (Ascend Data Center Solution) version is supported, you can reference to the installation guidelines https://www.mindspore.cn/install
[WARNING] ME(335241:281473363402784,MainProcess):2024-10-27-08:08:33.551.171 [mindspore/run_check/_check_version.py:380] Can not find ccec_compiler(need by mindspore-ascend), please check if you have set env PATH, you can reference to the installation guidelines https://www.mindspore.cn/install
[WARNING] ME(335241:281473363402784,MainProcess):2024-10-27-08:08:33.551.274 [mindspore/run_check/_check_version.py:385] Can not find tbe op implement(need by mindspore-ascend), please check if you have set env PYTHONPATH, you can reference to the installation guidelines https://www.mindspore.cn/install
[WARNING] ME(335241:281473363402784,MainProcess):2024-10-27-08:08:33.551.343 [mindspore/run_check/_check_version.py:391] Can not find driver so(need by mindspore-ascend), please check if you have set env LD_LIBRARY_PATH, you can reference to the installation guidelines https://www.mindspore.cn/install
[WARNING] ME(335241:281473363402784,MainProcess):2024-10-27-08:08:33.551.402 [mindspore/run_check/_check_version.py:397] Can not find opp path (need by mindspore-ascend), please check if you have set env ASCEND_OPP_PATH, you can reference to the installation guidelines https://www.mindspore.cn/install
Traceback (most recent call last):
  File "../train.py", line 19, in <module>
    import mindspore
  File "/home/mindocr/.conda/envs/ssd_ms18/lib/python3.7/site-packages/mindspore/__init__.py", line 17, in <module>
    from .run_check import run_check
  File "/home/mindocr/.conda/envs/ssd_ms18/lib/python3.7/site-packages/mindspore/run_check/__init__.py", line 17, in <module>
    from ._check_version import check_version_and_env_config
  File "/home/mindocr/.conda/envs/ssd_ms18/lib/python3.7/site-packages/mindspore/run_check/_check_version.py", line 455, in <module>
    check_version_and_env_config()
  File "/home/mindocr/.conda/envs/ssd_ms18/lib/python3.7/site-packages/mindspore/run_check/_check_version.py", line 439, in check_version_and_env_config
    env_checker.check_env(e)
  File "/home/mindocr/.conda/envs/ssd_ms18/lib/python3.7/site-packages/mindspore/run_check/_check_version.py", line 276, in check_env
    raise e
  File "/home/mindocr/.conda/envs/ssd_ms18/lib/python3.7/site-packages/mindspore/run_check/_check_version.py", line 436, in check_version_and_env_config
    from .. import _c_expression  # pylint: disable=unused-import
ImportError: libge_runner.so: cannot open shared object file: No such file or directory
